language: java

jdk: openjdk12

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2

before_deploy:
  - mvn javadoc:javadoc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/site/apidocs/
  on:
    branch: master